### ISSUE TITLE
There is no label window

### ISSUE THREAD

**Issue by theKoreyoshi** [denabazazian/Dual-Domain-Synthesis#2]
when i run save_segmentation_model.py,there is no label window, but just a image.

**Comment by denabazazian** [comment]
After running "save_segmentation_model.py", you should have a window with an image and a labelling tool beside the image, and then you can define the mask through that, this tool is based on [repurpose-gan](https://github.com/bryandlee/repurpose-gan) GitHub repository, it might be helpful if you check it.

**Comment by theKoreyoshi** [comment]
thanks for your answer,I have solved it.And there is an another question, why the code does not use pretrained vgg model?

**Comment by denabazazian** [comment]
It's great to hear that you have solved that. 
Regarding the VGG model, the [DDS_main.py](https://github.com/denabazazian/Dual-Domain-Synthesis/blob/main/DDS_main.py) code uses the VGG16 for Perceptual with the outputs of these four convolution layers conv1_1,conv1_2,conv2_2,conv3_3. You can follow this from line #318 of [DDS_main.py](https://github.com/denabazazian/Dual-Domain-Synthesis/blob/main/DDS_main.py). The details of loading the VGG16 can be found in [perceptual_model.py](https://github.com/denabazazian/Dual-Domain-Synthesis/blob/main/perceptual_model.py).
