### ISSUE TITLE
bad result 

### ISSUE THREAD

**Issue by emnab** [denabazazian/Dual-Domain-Synthesis#3]
![0231c50d-8aac-4015-8dc6-957f1d490e21](https://github.com/user-attachments/assets/35e84e83-ca86-4a93-8387-ad91d9d9511d)
bad result when running this code : 

!python DDS_main.py --generator_domain1_dir /content/Dual-Domain-Synthesis/550000.pt --generator_domain2_dir /content/Dual-Domain-Synthesis/550000.pt --segmentation_dir /content/Dual-Domain-Synthesis/input/eyes_nose_mouth/ --part_key eyes_nose_mouth --save_path_root /content/Dual-Domain-Synthesis/output/

**Comment by denabazazian** [comment]
Is the attached image your final results (`i_D2.png`)?
It seems like there is a problem with the generated images from `domain1` and `domain2`, have you checked the results from `generator_domain1` and `generator_domain2`
It would be helpful if you check the following images: 
- `org_source.png`
- `org_target.png`
- `naive_crossover_source.png`
- `naive_crossover_target.png`
If they look blurry similar to the picture you have attached, then you'll need to improve your generator model for domain1/2.

**Comment by emnab** [comment]
thank you for helping
